[PHP]
memory_limit           = 256M
upload_max_filesize    = 512M
post_max_size          = 512M
max_execution_time     = 300
max_input_vars         = 3000
display_errors         = Off
log_errors             = On
error_log              = /var/log/php_errors.log

[opcache]
opcache.enable                 = 1
opcache.validate_timestamps    = 1
opcache.revalidate_freq        = 0
opcache.max_accelerated_files  = 20000
opcache.memory_consumption     = 256
opcache.interned_strings_buffer = 16
opcache.fast_shutdown          = 1
